<a href="https://colab.research.google.com/github/LuisAngelOlveraOlvera/Grokking-Deep-Learning/blob/main/Chapter_6_building_your_first_deep_neural_network_introduction_to_backpropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Creating a matrix or two in Python

import numpy as np

streetlights = np.array([[1,0,1],
                        [0,1,1],
                        [0,0,1],
                        [1,1,1],
                        [0,1,1],
                        [1,0,1]])
print(streetlights)

walk_vs_stop = np.array([0,1,0,1,1,0])
print(walk_vs_stop)

[[1 0 1]
 [0 1 1]
 [0 0 1]
 [1 1 1]
 [0 1 1]
 [1 0 1]]
[0 1 0 1 1 0]


In [2]:
# Building a neural network
import numpy as np

weights = np.array([0.5, 0.48, -0.7])
alpha = 0.1

streetlights = np.array([[1,0,1],
                        [0,1,1],
                        [0,0,1],
                        [1,1,1],
                        [0,1,1],
                        [1,0,1]])

walk_vs_stop = np.array([0,1,0,1,1,0])

input = streetlights[0]
goal_prediction = walk_vs_stop[0]

for iterations in range(20):
  prediction = input.dot(weights)
  error = (goal_prediction - prediction)**2
  delta = prediction - goal_prediction
  weights_delta = input * delta
  weights = (weights - alpha * weights_delta)
  print("iterations: ",iterations,"Error: ", str(error) + "Prediction: ", str(prediction))

iterations:  0 Error:  0.03999999999999998Prediction:  -0.19999999999999996
iterations:  1 Error:  0.025599999999999973Prediction:  -0.15999999999999992
iterations:  2 Error:  0.01638399999999997Prediction:  -0.1279999999999999
iterations:  3 Error:  0.010485759999999964Prediction:  -0.10239999999999982
iterations:  4 Error:  0.006710886399999962Prediction:  -0.08191999999999977
iterations:  5 Error:  0.004294967295999976Prediction:  -0.06553599999999982
iterations:  6 Error:  0.002748779069439994Prediction:  -0.05242879999999994
iterations:  7 Error:  0.0017592186044416036Prediction:  -0.04194304000000004
iterations:  8 Error:  0.0011258999068426293Prediction:  -0.03355443200000008
iterations:  9 Error:  0.0007205759403792803Prediction:  -0.02684354560000002
iterations:  10 Error:  0.0004611686018427356Prediction:  -0.021474836479999926
iterations:  11 Error:  0.0002951479051793508Prediction:  -0.01717986918399994
iterations:  12 Error:  0.00018889465931478573Prediction:  -0.013743895

In [3]:
import numpy as np
weights = np.array([0.5, 0.48, -0.7])
alpha = 0.1

streetlights = np.array([[1,0,1],
                        [0,1,1],
                        [0,0,1],
                        [1,1,1],
                        [0,1,1],
                        [1,0,1]])

walk_vs_stop = np.array([0,1,0,1,1,0])

for iterations in range(40):
  error_for_all_lights = 0
  for row_index in range(len(walk_vs_stop)):
    input = streetlights[row_index]
    goal_prediction = walk_vs_stop[row_index]
    prediction = input.dot(weights)
    error = (goal_prediction - prediction)**2
    error_for_all_lights += error
    delta = prediction - goal_prediction
    weights_delta = input * delta
    weights = (weights - alpha * weights_delta)
    print("iterations: ",iterations,"Error: ", str(error_for_all_lights) + "Prediction: ", str(prediction))
  print("Error:" + str(error_for_all_lights) + "\n")

iterations:  0 Error:  0.03999999999999998Prediction:  -0.19999999999999996
iterations:  0 Error:  1.48Prediction:  -0.19999999999999996
iterations:  0 Error:  1.7935999999999999Prediction:  -0.5599999999999999
iterations:  0 Error:  1.9410559999999997Prediction:  0.6160000000000001
iterations:  0 Error:  2.62531584Prediction:  0.17279999999999995
iterations:  0 Error:  2.6561231104Prediction:  0.17552
Error:2.6561231104

iterations:  1 Error:  0.019716653055999997Prediction:  0.14041599999999999
iterations:  1 Error:  0.50045586768896Prediction:  0.3066464
iterations:  1 Error:  0.6195762723992576Prediction:  -0.34513824
iterations:  1 Error:  0.619620326734632Prediction:  1.006637344
iterations:  1 Error:  0.891578952113109Prediction:  0.4785034751999999
iterations:  1 Error:  0.9628701776715985Prediction:  0.26700416768
Error:0.9628701776715985

iterations:  2 Error:  0.04562638435743332Prediction:  0.213603334144
iterations:  2 Error:  0.26209136302679775Prediction:  0.534742029977

In [4]:
# Your first deep neural network

import numpy as np
np.random.seed(1)

def relu(x):
  return (x > 0) * x

alpha = 0.2
hidden_size = 4

streetlights = np.array([[1,0,1],
                         [0,1,1],
                         [0,0,1],
                         [1,1,1]])

walk_vs_stop = np.array([0,1,0,1]).T

weight_0_1 = 2 * np.random.random((3,hidden_size)) - 1
weight_1_2 = 2 * np.random.random((hidden_size,1)) - 1

layer_0 = streetlights[0]
layer_1 = relu(np.dot(layer_0, weight_0_1))
layer_2 = np.dot(layer_1, weight_1_2)

In [5]:
# Backpropagation in code
import numpy as np
np.random.seed(1)

def relu(x):
  return (x > 0) * x

def relu2deriv(output):
  return output>0

alpha = 0.2
hidde_size = 4

weights_0_1 = 2 * np.random.random((3,hidden_size)) - 1
weights_1_2 = 2 * np.random.random((hidden_size,1)) - 1

for iterations in range(60):
  layer_2_error = 0
  for i in range(len(streetlights)):
    layer_0 = streetlights[i:i+1]
    layer_1 = relu(np.dot(layer_0, weights_0_1))
    layer_2 = np.dot(layer_1,weights_1_2)
    layer_2_error += np.sum((layer_2 - walk_vs_stop[i:i+1]) ** 2)
    layer_2_delta = (walk_vs_stop[i:i+1] - layer_2)
    layer_1_delta = layer_2_delta.dot(weights_1_2.T)*relu2deriv(layer_1)

    weights_1_2 += alpha * layer_1.T.dot(layer_2_delta)
    weights_0_1 += alpha * layer_0.T.dot(layer_1_delta)
  if(iterations % 10 == 9):
    print("iteration: ", iterations, "Error:" + str(layer_2_error))





iteration:  9 Error:0.5099228249650793
iteration:  19 Error:0.07166336510555428
iteration:  29 Error:0.006545981611560201
iteration:  39 Error:0.0004490518255217955
iteration:  49 Error:2.7722546393920387e-05
iteration:  59 Error:1.660052964288212e-06


In [6]:
# one iteration backpropagation
# Initializing the network’s weights and data

import numpy as np

np.random.seed(1)

def relu(x):
  return (x > 0) * x

def relu2deriv(output):
  return output>0

lights = np.array( [[ 1, 0, 1 ],[ 0, 1, 1 ],[ 0, 0, 1 ],[ 1, 1, 1 ] ] )

walk_stop = np.array([[ 1, 1, 0, 0]]).T

alpha = 0.2
hidden_size = 3

weights_0_1 = 2*np.random.random((3,hidden_size)) - 1
weights_1_2 = 2*np.random.random((hidden_size,1)) - 1

print(weights_0_1)
print(weights_1_2)

[[-0.16595599  0.44064899 -0.99977125]
 [-0.39533485 -0.70648822 -0.81532281]
 [-0.62747958 -0.30887855 -0.20646505]]
[[ 0.07763347]
 [-0.16161097]
 [ 0.370439  ]]


In [7]:
# 2 PREDICT + COMPARE: Making a prediction, and calculating the output error and delta
layer_0 = lights[0:1]
layer_1 = np.dot(layer_0,weights_0_1)
layer_1 = relu(layer_1)
layer_2 = np.dot(layer_1,weights_1_2)

error = (layer_2-walk_stop[0:1])**2
layer_2_delta=(layer_2-walk_stop[0:1])

print("error", error)
print("layer_2_delta", layer_2_delta)

error [[1.0430446]]
layer_2_delta [[-1.02129555]]


In [8]:
# 3 LEARN: Backpropagating from layer_2 to layer_1

layer_0 = lights[0:1]
layer_1 = np.dot(layer_0,weights_0_1)
layer_1 = relu(layer_1)
layer_2 = np.dot(layer_1,weights_1_2)
error = (layer_2-walk_stop[0:1])**2
layer_2_delta=(layer_2-walk_stop[0:1])
layer_1_delta=layer_2_delta.dot(weights_1_2.T)
layer_1_delta *= relu2deriv(layer_1)

print("layer_1_delta", layer_1_delta)
print("error", error)
print("layer_2_delta", layer_2_delta)


layer_1_delta [[-0.          0.16505257 -0.        ]]
error [[1.0430446]]
layer_2_delta [[-1.02129555]]


In [9]:
# 4 LEARN: Generating weight_deltas, and updating weights
layer_0 = lights[0:1]
layer_1 = np.dot(layer_0,weights_0_1)
layer_1 = relu(layer_1)
layer_2 = np.dot(layer_1,weights_1_2)
error = (layer_2-walk_stop[0:1])**2
layer_2_delta=(layer_2-walk_stop[0:1])

layer_1_delta=layer_2_delta.dot(weights_1_2.T)
layer_1_delta *= relu2deriv(layer_1)

weight_delta_1_2 = layer_1.T.dot(layer_2_delta)
weight_delta_0_1 = layer_0.T.dot(layer_1_delta)
weights_1_2 -= alpha * weight_delta_1_2
weights_0_1 -= alpha * weight_delta_0_1

In [10]:
import numpy as np
np.random.seed(1)

def relu(x):
  return (x > 0) * x

def relu2deriv(output):
  return output>0

streetlights = np.array( [[ 1, 0, 1 ],[ 0, 1, 1 ],[ 0, 0, 1 ],[ 1, 1, 1 ] ] )

walk_vs_stop = np.array([[ 1, 1, 0, 0]]).T

alpha = 0.2
hidden_size = 4

weights_0_1 = 2*np.random.random((3,hidden_size)) - 1
weights_1_2 = 2*np.random.random((hidden_size,1)) - 1

for iteration in range(60):
  layer_2_error = 0
  for i in range(len(streetlights)):
    layer_0 = streetlights[i:i+1]
    layer_1 = relu(np.dot(layer_0,weights_0_1))
    layer_2 = np.dot(layer_1,weights_1_2)
    layer_2_error += np.sum((layer_2 - walk_vs_stop[i:i+1]) ** 2)
    layer_2_delta = (layer_2 - walk_vs_stop[i:i+1])
    layer_1_delta=layer_2_delta.dot(weights_1_2.T)*relu2deriv(layer_1)
    weights_1_2 -= alpha * layer_1.T.dot(layer_2_delta)
    weights_0_1 -= alpha * layer_0.T.dot(layer_1_delta)
  if(iteration % 10 == 9):
    print("Error:" + str(layer_2_error))

Error:0.6342311598444467
Error:0.35838407676317513
Error:0.0830183113303298
Error:0.006467054957103705
Error:0.0003292669000750734
Error:1.5055622665134859e-05


In [28]:
import numpy as np

np.random.seed(1)

def relu(x):
  return (x > 0) * x

alpha = 0.2
hidden_size = 4

streetlights = np.array([[1,0,1],
                         [0,1,1],
                         [0,0,1],
                         [1,1,1]])

walk_vs_stop = np.array([0,1,0,1]).T

weights_0_1 = 2*np.random.random((3,hidden_size)) - 1
weights_1_2 = 2*np.random.random((hidden_size,1)) - 1

layer_0 = streetlights[0]
layer_1 = relu(np.dot(layer_0, weights_0_1))
layer_2 = np.dot(layer_1, weights_1_2)

print("weights_0_1: \n ", weights_0_1)
print("\nweights_1_2: \n", weights_1_2)
print("\nlayer_0: \n", layer_0)
print("\nlayer_1: \n", layer_1)
print("\nlayer_2: \n", layer_2)



weights_0_1: 
  [[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]

weights_1_2: 
 [[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]

layer_0: 
 [1 0 1]

layer_1: 
 [-0.          0.51828245 -0.         -0.        ]

layer_2: 
 [0.39194327]


In [44]:
import numpy as np
np.random.seed(1)

def relu(x):
  return (x > 0) * x

def relu2deriv(output):
  return output>0

streetlights = np.array( [[ 1, 0, 1 ],[ 0, 1, 1 ],[ 0, 0, 1 ],[ 1, 1, 1 ] ] )

walk_vs_stop = np.array([[ 1, 1, 0, 0]]).T

alpha = 0.2
hidden_size = 4

weights_0_1 = 2*np.random.random((3,hidden_size)) - 1
weights_1_2 = 2*np.random.random((hidden_size,1)) - 1

for iteration in range(60):
  layer_2_error = 0
  for i in range(len(streetlights)):
    layer_0 = streetlights[i:i+1]
    print("\nlayer_0\n", layer_0)

    layer_1 = relu(np.dot(layer_0,weights_0_1))
    print("\nlayer_1\n", layer_1)

    layer_2 = np.dot(layer_1,weights_1_2)
    print("\nlayer_2\n", layer_2)

    layer_2_error += np.sum((layer_2 - walk_vs_stop[i:i+1]) ** 2)
    print("walk_vs_stop[i:i+1]: ", walk_vs_stop[i:i+1])
    print("\nlayer_2_error\n", layer_2_error)

    layer_2_delta = (layer_2 - walk_vs_stop[i:i+1])
    print("\nlayer_2_delta\n", layer_2_delta)

    layer_1_delta=layer_2_delta.dot(weights_1_2.T)*relu2deriv(layer_1)
    print("\nlayer_1_delta\n", layer_1_delta)

    weights_1_2 -= alpha * layer_1.T.dot(layer_2_delta)
    print("\nweights_1_2\n", weights_1_2)

    weights_0_1 -= alpha * layer_0.T.dot(layer_1_delta)
    print("\nweights_0_1\n", weights_0_1)

  if(iteration % 10 == 9):
    print("Error:" + str(layer_2_error))

Se han truncado las últimas 5000 líneas del flujo de salida.
 [[-0.45004457]]

layer_1_delta
 [[ 0.         -0.          0.         -0.28872139]]

weights_1_2
 [[-0.5910955 ]
 [ 1.13750938]
 [-0.94522481]
 [ 0.71869908]]

weights_0_1
 [[-0.16595599  0.90781564 -0.99977125 -0.59301887]
 [-0.70648822 -0.92794391 -0.62747958  0.45548659]
 [-0.20646505 -0.03583528 -0.16161097  0.51724518]]

layer_0
 [[0 0 1]]

layer_1
 [[-0.         -0.         -0.          0.51724518]]

layer_2
 [[0.37174364]]
walk_vs_stop[i:i+1]:  [[0]]

layer_2_error
 0.34131648249163804

layer_2_delta
 [[0.37174364]]

layer_1_delta
 [[-0.          0.         -0.          0.26717181]]

weights_1_2
 [[-0.5910955 ]
 [ 1.13750938]
 [-0.94522481]
 [ 0.68024256]]

weights_0_1
 [[-0.16595599  0.90781564 -0.99977125 -0.59301887]
 [-0.70648822 -0.92794391 -0.62747958  0.45548659]
 [-0.20646505 -0.03583528 -0.16161097  0.46381082]]

layer_0
 [[1 1 1]]

layer_1
 [[-0.         -0.         -0.          0.32627854]]

layer_2
 [[0.22

In [43]:
weights_0_1 = [[-0.16595599, 0.88701218, -0.99977125, -0.56206771],
               [-0.70648822, -0.92794391, -0.62747958, 0.37049171],
               [-0.20646505, -0.05663874, -0.16161097, 0.4854848]]
streetlights = np.array([ 1, 0, 1 ])
salida = np.dot(streetlights, weights_0_1)
print(salida)

def relu(x):
    return np.maximum(0, x)

salida = relu(salida)
print(salida)

[-0.37242104  0.83037344 -1.16138222 -0.07658291]
[0.         0.83037344 0.         0.        ]


In [14]:
weights_1_2 = 2*np.random.random((hidden_size,1)) - 1
print(weights_1_2)

[[-0.57674377]
 [-0.46890668]
 [-0.01685368]
 [-0.89327491]]
